version: 2.1

orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@0.0.10

workflows:
  run_test_and_deploy:
    jobs:
      - node/test:
          version: '15.1'
          filters:
            branches:
              only:
                - main
      - heroku/deploy-via-git:
          requires:
            - node/test
          filters:
            branches:
              only:
                - main
